def compose(*args, **kwargs) -> Any: ...
def identity(*args, **kwargs) -> Any: ...
def inverse(*args, **kwargs) -> Any: ...
def rotate(*args, **kwargs) -> Any: ...
def scale(*args, **kwargs) -> Any: ...
def skew(*args, **kwargs) -> Any: ...
def translate(*args, **kwargs) -> Any: ...
